### ISSUE TITLE
openadr_vtn20b_1 exited with code 1

### ISSUE THREAD

**Issue by 108618034** [avob/OpenADR#20]
i am using docker-compose up --build,  it stop at  "openadr_vtn20b_1 exited with code 1".
how can i fix it?

### vtn20b_1           | at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source) ~[?:?]
vtn20b_1           | at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
vtn20b_1           | at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:?]
vtn20b_1           | at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:856) ~[smack-tcp-4.3.4.jar!/:4.3.4]
vtn20b_1           | at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$2000(XMPPTCPConnection.java:155) ~[smack-tcp-4.3.4.jar!/:4.3.4]
vtn20b_1           | at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1171) ~[smack-tcp-4.3.4.jar!/:4.3.4]
vtn20b_1           | at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$1000(XMPPTCPConnection.java:1092) ~[smack-tcp-4.3.4.jar!/:4.3.4]
vtn20b_1           | at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1112) ~[smack-tcp-4.3.4.jar!/:4.3.4]
vtn20b_1           | at java.lang.Thread.run(Unknown Source) ~[?:?]
vtn20b_1           | [main] INFO  c.a.o.s.c.v.WebDestructor - Executer Oadr20DREventPushServiceExecutor- with active 0 work has killed
rabbitmq_1         | 2021-09-05 13:19:47.776 [info] <0.1477.0> closing AMQP connection <0.1477.0> (172.18.0.7:58140 -> 172.18.0.4:5672, vhost: '/', user: 'admin')
rabbitmq_1         | 2021-09-05 13:19:47.794 [info] <0.1484.0> closing AMQP connection <0.1484.0> (172.18.0.7:58142 -> 172.18.0.4:5672, vhost: '/', user: 'admin')
openadr_vtn20b_1 exited with code 1

**Comment by zanni** [comment]
look like your openfire (xmpp broker) middleware wasn’t up so when vtn tried to make the ssl handshake it failed (unknown source).

**Comment by 108618034** [comment]
Thanks for your response,

so i have to open openfire fisrt?( http://localhost:9090) 
Is there any setting to set?

**Comment by 108618034** [comment]
> 感謝您的答复，
> 
> 所以我必須打開openfire fisrt？（http://localhost:9090）
> 有什麼設置要設置嗎？

it seems to have successfully installed.

openfire_1         |   http://xmpp.vtn.oadr.com:9090
openfire_1         |   https://xmpp.vtn.oadr.com:9091
openfire_1         | Successfully loaded plugin 'admin'.
openfire_1         | Successfully loaded plugin 'openfireoadrplugin-openfire-plugin-assembly'.
openfire_1         | Successfully loaded plugin 'search'.
openfire_1         | Finished processing all plugins.

**Comment by zanni** [comment]
docker-compose up --build
is supposed to set up everything for you. Ensure every middle have been correctly initialized before VTN / drprogram / VEN. Ensure certificates are installed into your local repo to access UI.

It’s been a while (less than a year) I did not launch this demo so slight changes might be required to adapt to new version of some tool. Recent versions of docker-compose are not compatible for example (tested with 1.28.5).

**Comment by zanni** [comment]
Then did you success to launch the VTN ?

**Comment by 108618034** [comment]
no i didn't succeed.
i am work on at ubuntu 18.04  docker-compose version 1.25.5.
so i have to chang to 1.28.5?

**Comment by bbartling** [comment]
Im on Ubuntu 20.04 and got the docker build to work. I also posted some links on my issue for getting the correct docker compose version if it helps at all. How do you launch the VTN when build success?

**Comment by 108618034** [comment]
i work on  ubuntu 18.04   docker-compose  1.28.5, and it seem it was work,
but i can't open  https://vtn.oadr.com:8181/testvtn/,however i can open RabbitMQ  and Openfire .

**Comment by zanni** [comment]
Hi,

I committed a file containing the logs of a successful demo start on master branch:
https://github.com/avob/OpenADR/blob/master/successfull_build.txt

Multiple things happenning:
- build image run, compile app if it's not yet done. This image will be stopped when everything has been provided to further images
- middleware image starts: postgres_1, openfire_1, rabbitmq_1
- vtn image starts: vtn20b_1
- drprogram starts: dummy-drprogram_1
- ven starts: ven20b_1
- then VTN / DRP / VEN starts interacting as described in README file.

This demo has been launched on macOS, with Docker version 20.10.5, build 55c4c88 and docker-compose version 1.28.5, build c4eb3a1f

This process described in README has been followed i.e certificates are generated correctly, vtn.oadr.com has been added to DNS provider, admin certificates has been added to browser certificates provider (required to access VTN UI).

Hope it will help

**Comment by 108618034** [comment]
Thanks for your response,
i have a question about the certificates, 
how can i add  admin certificates to browser certificates provider(use ./generate_test_cert.sh ?)

**Comment by zanni** [comment]
This step depends wildly on your browser / system. For example in Firefox / windows, a client certificate seems to be added like this:
https://support.globalsign.com/digital-certificates/digital-certificate-installation/install-client-digital-certificate-firefox-windows <https://support.globalsign.com/digital-certificates/digital-certificate-installation/install-client-digital-certificate-firefox-windows>

Client certificate has been generated by generate_test_cert.sh and are located in ./cert folder.
Multiple user are generated, including users used by java apps (vtn / ten …).

You should use admin.* certificates, it can be admin.oadr.com.p12 (as in the tuto), or it can be admin.oadr.com.key + admin.oadr.com.crt (postman http client for example).

**Comment by zanni** [comment]
Your local DNS might not be set up : vtn.oadr.com <http://vtn.oadr.com/> should be set to local ip (127.0.0.1)

**Comment by parashar18** [comment]
> 

I am facing the same issue. Did you able to run https://vtn.oadr.com:8181/testvtn/ and https://vtn.oadr.com:8181/testvtn/swagger-ui.html?
